package com.example.maintenance.issue.add_issue.model_add_issue

data class Data(
    var action_taken: String,

    var custom_assign_user: String,
//    val custom_assign_user_time: String,
    var custom_contact_person: String,
    var custom_customer_signature: String,
    var custom_department: String,
//    val custom_live_customer_signature: String,
    var custom_location: String,
    var custom_material_used: ArrayList<CustomMaterialUsed>,
    var custom_mob_number: String,
    var custom_office: String,
//    val custom_waiting_period: String,
    var customer: String,
    var customer_remarks: String,
//    val docstatus: Int,
//    val doctype: String,
//    val idx: Int,
//    val is_block: Int,
    var issue_type: String,
//    val locality: String,
//    val modified: String,
//    val modified_by: String,
//    val name: String,
//    val naming_series: String,
//    val number_of_visit: String,
//    val opening_date: String,
//    val opening_time: String,
//    val owner: String,
//    val part_name: String,
    var priority: String,
    var raised_by: String,
//    val resolution_by: String,
//    val response_by: String,
//    val service_level_agreement: String,
    var status: String,
    var subject: String,
//    val via_customer_portal: Int,
//    val visit_charge: String,
//    val warranty_status: String,
    var description: String,
    var resolution_details: String
)